### PR TITLE
Homescreen design/redesign

### PR DESCRIPTION
**Pull request by Lohit9**
Tried to make the home screen a little more appealing. Changes made are:
- add circular profile pic view to the home screen
- add help text to make sure the user selects a location before logging in 
- some other design modifications (add color to the log in button, add text to log in button, positioning)
- Add back button for log in activity so that user can go back to the main activity

This is how it will look after this PR is merged:
screen shot 2018-02-27 at 7 32 23 pm

Please review @n0thingness @n4ho

### CODE REVIEW

**Comment by dbxe** [comment]
@Lohit9 

In the build.gradle, the circle image view library is included twice

What is the purpose of the textview below the login button? If the user is already logged in ("Welcome, Kitty"), why is there a button below to link to the login page? Also, wouldn't the user need to log in prior to checking in to a location?

We can remove the back-blocking functionality of the login window for demo purposes but I think once server side login is working properly, it makes sense to force unauthenticated users to stay on the login page.

**Comment by Lohit9** [comment]
@n0thingness 

- thanks removed the duplicate line from the build.gradle file 
- I'm sorry I was confused about the flow of the app, fixed it
- Ok 
looks like this:

screen shot 2018-02-28 at 7 47 15 pm


Thanks for the feedback. Please take another look @n4ho @n0thingness

**Comment by Lohit9** [comment]
Do we still want a button on this activity? Because earlier we used to have a button. We still need something to transition over to the next activity

**Comment by n4ho** [comment]
I think we need a "logout" button to go back to the login page, and a "view my profile" button to go to the user profile page. The buttons can be hidden in a side menu so the page will look cleaner.

**Pull request merged**
